import "./globals.css";
import localFont from "next/font/local";
import TopNav from "../components/topnav/topnav";
import Sidebar from "../components/sidebar/sidebar";
import ApolloContainer from "../providers/apollo-provider";
import { Metadata } from "next";

const notoSans = localFont({
  src: "./fonts/NotoSans-VariableFont_wdth,wght.ttf",
  variable: "--font-noto-sans",
  weight: "500 600 900",
});
const notoMono = localFont({
  src: "./fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf",
  variable: "--font-noto-mono",
  weight: "500 600 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoMono.variable} antialiased flex flex-col min-h-[100vh]`}
      >
        <ApolloContainer>
          <TopNav />
          <div className="flex">
            <Sidebar />
            <main className="py-8 pl-4 md:pl-16">{children}</main>
          </div>
        </ApolloContainer>
      </body>
    </html>
  );
}
